### ISSUE TITLE
部署后无法使用，caddy报错

### ISSUE THREAD

**Issue by mlch911** [kszym2002/ssrpanel-be#1]
部署后，开放了防火墙，还是无法使用，caddy已经获取到了证书，但是报了错误，然后就没有了，v2ray也连不上，不知道我哪儿出问题了……

Sending telemetry (attempt 3): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying

**Comment by kszym2002** [comment]
.... v2ray path设置正确吗? 请把v2 config.json 和 Caddyfile 展示出来 域名隐藏
