### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by Helpayment** [kszym2002/ssrpanel-be#2]
大佬您好，这个是我面板参数
![image](https://user-images.githubusercontent.com/32597550/49329001-22b4e900-f5b4-11e8-83ff-6d413d25df90.png)

config.properties文件中，我只将数据库参数修改成我的，config.json未修改，[
root@VMVM-181201-7VNJ caddy]# vi Caddyfile 

www.h3k2.fun
{
  root /srv/www
  tls 我的QQ@qq.com
  proxy /panda v2ray:990 {
    websocket
    header_upstream -Origin
  }
}

**日志输出是**[root@VMVM-181201-7VNJ caddy]# docker-compose logs v2ray
Attaching to caddy_v2ray_1_20b3998eeb00
v2ray_1_20b3998eeb00 |   __  __ _           _           _   _      _
v2ray_1_20b3998eeb00 |  |  \/  (_)___  __ _| | ____ _  | \ | | ___| |_
v2ray_1_20b3998eeb00 |  | |\/| | / __|/ _` | |/ / _` | |  \| |/ _ \ __|
v2ray_1_20b3998eeb00 |  | |  | | \__ \ (_| |   < (_| | | |\  |  __/ |_
v2ray_1_20b3998eeb00 |  |_|  |_|_|___/\__,_|_|\_\__,_| |_| \_|\___|\__|
v2ray_1_20b3998eeb00 | 
v2ray_1_20b3998eeb00 | V2Ray 4.7.0 (Po) 20181129
v2ray_1_20b3998eeb00 | A unified platform for anti-censorship.
v2ray_1_20b3998eeb00 | 2018/12/01 21:20:00 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
v2ray_1_20b3998eeb00 | 2018/12/01 21:20:00 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
v2ray_1_20b3998eeb00 | 2018/12/01 21:20:32 [ERROR] com.zaxxer.hikari.pool.HikariPool: HikariPool-1 - Exception during pool initialization.  
v2ray_1_20b3998eeb00 | com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
v2ray_1_20b3998eeb00 | 
v2ray_1_20b3998eeb00 | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:832)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
v2ray_1_20b3998eeb00 | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.utils.DbUtil.<clinit>(DbUtil.java:18)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayDao.<init>(V2rayDao.java:35)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayDao.getInstance(V2rayDao.java:126)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayGrpc.<init>(V2rayGrpc.java:54)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayGrpc.getInstance(V2rayGrpc.java:275)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayDestroyer.add(V2rayDestroyer.java:24)
v2ray_1_20b3998eeb00 | 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:353)
v2ray_1_20b3998eeb00 | 	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
v2ray_1_20b3998eeb00 | 	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
v2ray_1_20b3998eeb00 | 	at java.lang.Thread.run(Thread.java:745)
v2ray_1_20b3998eeb00 | Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
v2ray_1_20b3998eeb00 | 
v2ray_1_20b3998eeb00 | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
v2ray_1_20b3998eeb00 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
v2ray_1_20b3998eeb00 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
v2ray_1_20b3998eeb00 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
v2ray_1_20b3998eeb00 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:952)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822)
v2ray_1_20b3998eeb00 | 	... 20 more
v2ray_1_20b3998eeb00 | Caused by: java.net.SocketTimeoutException: connect timed out
v2ray_1_20b3998eeb00 | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
v2ray_1_20b3998eeb00 | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
v2ray_1_20b3998eeb00 | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
v2ray_1_20b3998eeb00 | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
v2ray_1_20b3998eeb00 | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
v2ray_1_20b3998eeb00 | 	at java.net.Socket.connect(Socket.java:589)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:173)
v2ray_1_20b3998eeb00 | 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
v2ray_1_20b3998eeb00 | 	... 23 more
v2ray_1_20b3998eeb00 | Exception in thread "Exec Default Executor" java.lang.NoClassDefFoundError: Could not initialize class cn.moegezi.v2ray.node.utils.DbUtil
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayDao.<init>(V2rayDao.java:35)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayDao.getInstance(V2rayDao.java:126)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayGrpc.<init>(V2rayGrpc.java:54)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayGrpc.getInstance(V2rayGrpc.java:275)
v2ray_1_20b3998eeb00 | 	at cn.moegezi.v2ray.node.process.V2rayDestroyer.remove(V2rayDestroyer.java:38)
v2ray_1_20b3998eeb00 | 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:411)
v2ray_1_20b3998eeb00 | 	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
v2ray_1_20b3998eeb00 | 	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
v2ray_1_20b3998eeb00 | 	at java.lang.Thread.run(Thread.java:745)
v2ray_1_20b3998eeb00 |   __  __ _           _           _   _      _
v2ray_1_20b3998eeb00 |  |  \/  (_)___  __ _| | ____ _  | \ | | ___| |_
v2ray_1_20b3998eeb00 |  | |\/| | / __|/ _` | |/ / _` | |  \| |/ _ \ __|
v2ray_1_20b3998eeb00 |  | |  | | \__ \ (_| |   < (_| | | |\  |  __/ |_
v2ray_1_20b3998eeb00 |  |_|  |_|_|___/\__,_|_|\_\__,_| |_| \_|\___|\__|
v2ray_1_20b3998eeb00 | 
v2ray_1_20b3998eeb00 | V2Ray 4.7.0 (Po) 20181129
v2ray_1_20b3998eeb00 | A unified platform for anti-censorship.
v2ray_1_20b3998eeb00 | 2018/12/01 21:28:57 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
v2ray_1_20b3998eeb00 | 2018/12/01 21:28:57 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
v2ray_1_20b3998eeb00 | 2018/12/01 21:29:00 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.  
v2ray_1_20b3998eeb00 | 2018/12/01 21:29:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:29:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.46 0.28 0.25  
v2ray_1_20b3998eeb00 | 2018/12/01 21:29:05 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 更新用户: ADD 86 REMOVE 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:30:02 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:30:02 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.72 0.43 0.30  
v2ray_1_20b3998eeb00 | 2018/12/01 21:31:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:31:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.53 0.41 0.30  
v2ray_1_20b3998eeb00 | 2018/12/01 21:32:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:32:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.19 0.34 0.28  
v2ray_1_20b3998eeb00 | 2018/12/01 21:33:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:33:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.48 0.39 0.30  
v2ray_1_20b3998eeb00 | 2018/12/01 21:34:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:34:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.61 0.44 0.32  
v2ray_1_20b3998eeb00 | 2018/12/01 21:35:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:35:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.22 0.36 0.30  
v2ray_1_20b3998eeb00 | 2018/12/01 21:36:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:36:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.16 0.32 0.29  
v2ray_1_20b3998eeb00 | 2018/12/01 21:37:02 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:37:02 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.89 0.45 0.33  
v2ray_1_20b3998eeb00 | 2018/12/01 21:38:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:38:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.38 0.38 0.31  
v2ray_1_20b3998eeb00 | 2018/12/01 21:39:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:39:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.37 0.41 0.33  
v2ray_1_20b3998eeb00 | 2018/12/01 21:40:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:40:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.14 0.33 0.30  
v2ray_1_20b3998eeb00 | 2018/12/01 21:41:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:41:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.11 0.29 0.28  
v2ray_1_20b3998eeb00 | 2018/12/01 21:42:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:42:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.16 0.27 0.28  
v2ray_1_20b3998eeb00 | 2018/12/01 21:43:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:43:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.24 0.28 0.28  
v2ray_1_20b3998eeb00 | 2018/12/01 21:44:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:44:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.08 0.23 0.26  
v2ray_1_20b3998eeb00 | 2018/12/01 21:45:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:45:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.03 0.18 0.24  
v2ray_1_20b3998eeb00 | 2018/12/01 21:46:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:46:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.11 0.18 0.23  
v2ray_1_20b3998eeb00 | 2018/12/01 21:47:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:47:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.04 0.14 0.22  
v2ray_1_20b3998eeb00 | 2018/12/01 21:48:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:48:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.01 0.11 0.20  
v2ray_1_20b3998eeb00 | 2018/12/01 21:49:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:49:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.28 0.17 0.21  
v2ray_1_20b3998eeb00 | 2018/12/01 21:50:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:50:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.37 0.20 0.21  
v2ray_1_20b3998eeb00 | 2018/12/01 21:51:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:51:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.13 0.16 0.20  
v2ray_1_20b3998eeb00 | 2018/12/01 21:52:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:52:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.37 0.20 0.20  
v2ray_1_20b3998eeb00 | 2018/12/01 21:53:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
v2ray_1_20b3998eeb00 | 2018/12/01 21:53:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.13 0.16 0.18  
v2ray_1_20b3998eeb00 | 2018/12/01 21:54:01 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0

**Comment by kszym2002** [comment]
第一次保存 没链接到数据库 第二次重启 链接数据库成功 开始更新用户 成功  添加了86个用户
